### ISSUE TITLE
Does not work with `quic-go` 0.53.0

### ISSUE THREAD

**Issue by merlinz01** [imroc/req#442]
I get these errors when building a project using `github.com/imroc/req@v3.53.0` and `github.com/quic-go/quic-go@v0.53.0`:
```
# github.com/imroc/req/v3/internal/http3
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/conn.go:43:7: undefined: quic.Connection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/conn.go:66:16: undefined: quic.Connection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/frames.go:24:27: undefined: quic.Connection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/trace.go:22:12: undefined: quic.EarlyConnection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/transport.go:49:18: undefined: quic.EarlyConnection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/transport.go:79:90: undefined: quic.EarlyConnection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/transport.go:111:26: undefined: quic.EarlyConnection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/client.go:79:12: undefined: quic.Connection
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/http_stream.go:60:16: cannot use &stream{} (value of type *stream) as Stream value in variable declaration: *stream does not implement Stream (*stream missing in github.com/quic-go/quic-go.Stream)
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/http_stream.go:164:23: cannot use &requestStream{} (value of type *requestStream) as RequestStream value in variable declaration: *requestStream does not implement RequestStream (*requestStream missing in github.com/quic-go/quic-go.Stream)
../../../go/pkg/mod/github.com/imroc/req/v3@v3.51.0/internal/http3/http_stream.go:164:23: too many errors
```

Downgrading `quic-go` to 0.52.0 is a temporary fix.

**Comment by imroc** [comment]
quic-go v0.53.0 has very big changes, which will take some time to adapt

**Comment by imroc** [comment]
Now, req v3.54.0 is released, which compatible with quic-go v0.53.0
